import { Inter } from "next/font/google";
import "./style/globals.css";
import { Navbar } from "@/app/components/Navbar";
import "zenn-content-css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className=" min-h-screen overflow-x-hidden">
          <Navbar />
          <div className=" w-hull h-full min-h-screen bg-[#ecf3f8]">
            <div className=" mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-[1120px] xl:px-0">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
